language: go
go:
  - 1.9
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username luoluomeng --token $GITHUB_TOKEN --recreate --prerelease --debug pre-release dist/